package notion

import "time"

// generated by chatGPT
type APIResponse struct {
	Object     string                 `json:"object"`
	Results    []APIResult            `json:"results"`
	NextCursor bool                   `json:"next_cursor"`
	HasMore    bool                   `json:"has_more"`
	Type       string                 `json:"type"`
	Block      map[string]interface{} `json:"block"`
	RequestId  string                 `json:"request_id"`
}

type APIResult struct {
	Object           string       `json:"object"`
	Id               string       `json:"id"`
	Parent           APIParent    `json:"parent"`
	CreatedTime      time.Time    `json:"created_time"`
	LastEditedTime   time.Time    `json:"last_edited_time"`
	CreatedBy        APIUser      `json:"created_by"`
	LastEditedBy     APIUser      `json:"last_edited_by"`
	HasChildren      bool         `json:"has_children"`
	Archived         bool         `json:"archived"`
	InTrash          bool         `json:"in_trash"`
	Type             string       `json:"type"`
	Paragraph        *APIRichText `json:"paragraph,omitempty"`
	BulletedListItem *APIRichText `json:"bulleted_list_item,omitempty"`
}

type APIParent struct {
	Type    string `json:"type"`
	BlockId string `json:"block_id"`
}

type APIUser struct {
	Object string `json:"object"`
	Id     string `json:"id"`
}

type APIRichText struct {
	RichText []APIPlainText `json:"rich_text"`
}

type APIPlainText struct {
	Type      string `json:"type"`
	PlainText string `json:"plain_text"`
}
