# This workflow will build a golang project
# Original source: https://github.com/actions/starter-workflows/blob/main/ci/go.yml
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Thanksfulness CI

on:
  pull_request:
    # About types See https://docs.github.com/ja/webhooks/webhook-events-and-payloads#pull_request
    types: [opened, reopened, ready_for_review, synchronize]
    paths:
      - 'thanksfulness/**'
      - '!thanksfulness/docs/**'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Go environment
        id: setup-go
        uses: actions/setup-go@v5.0.0
        with:
          go-version-file: 'thanksfulness/go.mod'
          # See https://tech.yappli.io/entry/setup-go-v4
          cache-dependency-path: 'thanksfulness/go.sum'

      - name: Download Go modules
        shell: bash
        if: ${{ steps.setup-go.outputs.cache-hit != 'true' }}
        working-directory: thanksfulness
        run: go mod download

      - name: Build
        # See: https://ebc-2in2crc.hatenablog.jp/entry/2023/01/13/181801
        working-directory: thanksfulness
        run: go build -o thanksfulness

      - name: Test
        working-directory: thanksfulness
        run: go test -v ./...

      - name: Upload Go Built File
        uses: actions/upload-artifact@v4
        with:
          name: built-thanksfulness
          path: ./thanksfulness/thanksfulness
