# See: https://github.com/actions/starter-workflows/blob/main/deployments/google-cloudrun-docker.yml
name: Thanksfulness Deploy

on:
  push:
    branches:
      - 'main'
      - 'feature/setup-deploy-action' # FIXME あとで消す
  workflow_dispatch:

defaults:
  run:
    # See: https://ebc-2in2crc.hatenablog.jp/entry/2023/01/13/181801
    working-directory: thanksfulness

jobs:
  build-and-push-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # FIXME 確認用。あとで消す
      - run: pwd
      - run: ls -la

      # See https://github.com/google-github-actions/auth
      - name: Authenticate with Google Cloud
        uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      # See https://github.com/google-github-actions/setup-gcloud?tab=readme-ov-file#setup-gcloud-github-action
      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v2'
        with:
          version: '>= 456.0.0'

      - name: Configure Docker client
        run: gcloud auth configure-docker asia-northeast1-docker.pkg.dev

      # https://matsuand.github.io/docs.docker.jp.onthefly/language/golang/configure-ci-cd/#optimizing-the-workflow

      # TODO キャッシュをうまく使えるようにする See https://docs.docker.com/build/ci/github-actions/cache/
      # - name: Set up Docker Buildx
      #   id: buildx
      #   uses: docker/setup-buildx-action@v3

      # - name: Cache Docker layers
      #   uses: actions/cache@v2
      #   with:
      #     path: /tmp/.buildx-cache
      #     key: ${{ runner.os }}-buildx-${{ github.sha }}
      #     restore-keys: |
      #       ${{ runner.os }}-buildx-

      - name: Build and push Docker image
        id: docker_build
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: asia-northeast1-docker.pkg.dev/${{ env.GCP_PROJECT }}/thanksfulness:latest
          # builder: ${{ steps.buildx.outputs.name }}
          # cache-from: type=local,src=/tmp/.buildx-cache
          # cache-to: type=local,dest=/tmp/.buildx-cache

      - name: Echo image digest
        run: echo ${{ steps.docker_build.outputs.digest }}

      # TODO Artifact Registry に push
      - name: Push Docker image to AR
        run: pwd

      # TODO Cloud Run にデプロイ
      - name: Deploy Cloud Run
        run: pwd
