# See: https://github.com/actions/starter-workflows/blob/main/deployments/google-cloudrun-docker.yml
name: Thanksfulness Deploy Cloud Run

on:
  push:
    branches:
      - 'main'
      - 'feature/setup-deploy-action' # FIXME あとで消す
  workflow_dispatch:

defaults:
  run:
    # See: https://ebc-2in2crc.hatenablog.jp/entry/2023/01/13/181801
    working-directory: thanksfulness

jobs:
  build-and-push-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Chackout
        uses: actions/checkout@v4

      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: built-thanksfulness
          # path: ./ # 保存先 path を指定したい場合に使用する

      # FIXME 確認用。あとで消す
      - run: pwd
      - run: ls -la

      # See https://github.com/google-github-actions/auth
      - name: Authenticate with Google Cloud
        uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Configure Docker client
        run: gcloud auth configure-docker

      # TODO Dockerfile をもとにイメージをビルド
      - name: Build Docker image
        run: pwd

      # TODO Artifact Registry に push
      - name: Push Docker image to AR
        run: pwd

      # TODO Cloud Run にデプロイ
      - name: Deploy Cloud Run
        run: pwd
