# See: https://github.com/actions/starter-workflows/blob/main/deployments/google-cloudrun-docker.yml
name: Thanksfulness Deploy Cloud Run

on:
  push:
    branches:
      - 'main'
  workflow_dispatch:

defaults:
  run:
    # See: https://ebc-2in2crc.hatenablog.jp/entry/2023/01/13/181801
    working-directory: thanksfulness

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
